# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: goals-api
# app and org for use with dashboard.serverless.com
app: goals-app
org: cperdue

package: 
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod 
  region: us-east-2
  lambdaHashingVersion: 20201221

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
        - s3:GetObject
      Resource: "arn:aws:dynamodb:us-east-2:*:*"


functions:
  create:
    handler: create.main
    events:
      - http:
          path: goals
          method: post
          cors: true
          authorizer: aws_iam
  list:
    handler: list.main
    events:
      - http:
          path: goals
          method: get
          cors: true
          authorizer: aws_iam
  delete:
    handler: delete.main
    events:
      - http:
          path: goals
          method: delete
          cors: true
          authorizer: aws_iam
